version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 311141533685.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - docker build -t ecs-demo-app:latest .
      - docker tag ecs-demo-app:latest 311141533685.dkr.ecr.us-east-1.amazonaws.com/ecs-demo-app:latest

  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push 311141533685.dkr.ecr.us-east-1.amazonaws.com/ecs-demo-app:latest
      - echo Creating imagedefinitions.json...
      - printf '[{"name":"ecs-demo-container","imageUri":"311141533685.dkr.ecr.us-east-1.amazonaws.com/ecs-demo-app:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
